---

services:
  app:
    build: .
    # image: ghcr.io/hargata/lubelogger:edge
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./data:/App/data
      - ./keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 8080:8080

volumes:
  data:
  keys: